### ISSUE TITLE
Support for null safety.

### ISSUE THREAD

**Issue by pratikpparikh** [lexaknyazev/wasm.dart#1]
Could you please add support for null safety

**Comment by pratikpparikh** [comment]
#2

**Comment by pratikpparikh** [comment]
@lexaknyazev can you please provide any update?

**Comment by zsyphon** [comment]
Hi @lexaknyazev I am hoping this gets resolved soon. Do you know when we can  expect it to be finished? Any updates yet? Thank you!!!

**Comment by EP-u-NW** [comment]
null safety would be very nice! If you need any help with this, let us know 😄

**Comment by lexaknyazev** [comment]
Apologies for the delay here. Apparently, not all browsers fully implement the current WebAssembly IDL. On top of that, Dart doesn't automatically map its `BigInt` type to the same JS type thus complicating interactions with 64-bit integers.

I have the wrapper with null safely, 64-bit integer helpers, and `externref` support ready. Working on completing test coverage atm.

**Comment by zsyphon** [comment]
@lexaknyazev thank you! I am looking forward to testing the added support!

**Comment by pratikpparikh** [comment]
@lexaknyazev please let me know when you have checked this in I will test it out and let you know what I find.

**Comment by pratikpparikh** [comment]
@lexaknyazev Thank you,  I will test out the changes for new 2.0 version and report any problems as soon as possible.
