### ISSUE TITLE
how to use this lib to interact with a webassembly lib like photon_rs for example

### ISSUE THREAD

**Issue by insinfo** [lexaknyazev/wasm.dart#4]
how to use this lib to interact with a webassembly lib like photon_rs for example

I have an AngularDart project and I need to interact with the "photon" lib to resize and compress images before uploading

https://github.com/insinfo/photon-test/blob/master/pkg/photon_rs_bg.wasm
https://silvia-odwyer.github.io/photon/

**Comment by lexaknyazev** [comment]
This package only wraps the low-level WebAssembly JavaScript API and is not intended for use with libraries that require custom "glue" code (like phantom_rs). The proper way of interacting with such libraries from Dart on the web is to call into their official JS "glue" via `package:js`.

**Comment by insinfo** [comment]
@lexaknyazev 
I cloned the code from the "photon_rs" library, and I'm going to make some modifications so that I can an ArrayBuffer/Blob from an image file straight to it, so I don't need to keep creating CanvasElement, I'll recompile this lib made in rust, you would have any simple examples of how to call WebAssembly functions straight from dart with your lib ?
