### ISSUE TITLE
Functions are named differently in the wasm instance

### ISSUE THREAD

**Issue by devopsi** [lexaknyazev/wasm.dart#5]
hello lexaknyazev,
I am using your great package to instantiate wasm module from dart. Can you please help me with this issue : 
https://stackoverflow.com/questions/68316438/how-to-get-variables-value-from-custom-js-and-use-it-in-flutter-web-dart
I really don't now how to solve it.

**Comment by lexaknyazev** [comment]
That module is compiled with emscripten and must be used with JS glue code (`el-passo-idp.js`) that handles instantiation and provides function name mappings. To integrate such a module with Flutter, you's need to write Dart bindings to that JS glue code instead of instantiating it manually.

**Comment by devopsi** [comment]
Oh thank you for your answer!
"you's need to write Dart bindings to that JS glue code instead of instantiating it manually."

can you please give me an exemple of what I have to do

**Comment by EP-u-NW** [comment]
Maybe section 3 from [this](https://github.com/EPNW/web_ffi/tree/master/example) can help you
