### ISSUE TITLE
Got  WebAssembly.instantiate(): Imports argument must be present and must be an object

### ISSUE THREAD

**Issue by pingpingpang001** [lexaknyazev/wasm.dart#6]
Instance.fromBytesAsync
from assets,but got error WebAssembly.instantiate(): Imports argument must be present and must be an object

**Comment by lexaknyazev** [comment]
This runtime error means that the specific module that is being instantiated requires an imports object, which was not provided.

**Comment by ranulfo** [comment]
I had the same problem.
A .wasm file generated using typescript code worked perfectly.
(see here: https://blog.logrocket.com/getting-started-webassembly-flutter-web/ )
However, in a .wasm file generated using C# code  ( see here:  https://www.fermyon.com/blog/dotnet-wasi) , I receive this same error.
